general {
    hide_cursor = true
    grace = 2
}

background {
    monitor =
    path = /home/cte/Dropbox/Personal/Backgrounds/catppuccin-clouds-3.png
    blur_passes = 3
    blur_size = 6
    noise = 0.01
    contrast = 0.95
    brightness = 0.8
    vibrancy = 0.15
    vibrancy_darkness = 0.2
}

input-field {
    monitor =
    size = 260, 52
    outline_thickness = 2
    dots_size = 0.22
    dots_spacing = 0.18
    dots_center = true
    outer_color = rgba(cba6f7cc)
    inner_color = rgba(30, 30, 46, 0.60)
    font_color = rgba(205, 214, 244, 1.0)
    fade_on_empty = false
    placeholder_text = <span foreground="##a6adc8">password</span>
    position = 0, -20
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:1000] echo "$(date +'%I:%M')"
    color = rgba(205, 214, 244, 1.0)
    font_size = 52
    position = 0, 80
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:1000] echo "$(date +'%A, %B %d')"
    color = rgba(166, 173, 200, 1.0)
    font_size = 16
    position = 0, 26
    halign = center
    valign = center
}
